# Copyright © 2026 Giovanni Squillero / Politecnico di Torino
# https://github.com/squillero/programmer-zendo
# Free under certain conditions — see the license for details.

[project]
name = "pythonic-bst"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Giovanni Squillero", email = "giovanni.squillero@polito.it" }
]
requires-python = ">=3.13"
dependencies = [
    "pytest>=9.1.1",
]

[project.scripts]
pythonic-bst = "pythonic_bst:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
