# ___  _   _ ___ _  _ ____ _  _ _ ____    ___  ____ ___
# |__]  \_/   |  |__| |  | |\ | | |       |__] [__   |
# |      |    |  |  | |__| | \| | |___    |__] ___]  |
#
# Copyright © 2023 Giovanni Squillero / Politecnico di Torino
# https://github.com/squillero/programmer-zendo
# Free under certain conditions — see the license for details.

[project]
    name = "bst"
    version = "1.0.3"
    description = "A minimalistic, unbalanced Binary Search Tree written in pure Python."
    readme = "README.md"
    authors = [
        { name = "Giovanni Squillero", email = "giovanni.squillero@polito.it" },
    ]
    requires-python = ">=3.10"
    dependencies = [
    "pytest>=9.1.1",
]

    [project.scripts]
        pythonic-bst = "pythonic_bst:main"

[build-system]
    requires      = ["uv_build>=0.12.3,<0.13.0"]
    build-backend = "uv_build"
